"""Dummy Column remove

Revision ID: 9c5a8717d0cd
Revises: 978aa1ff34a8
Create Date: 2025-09-12 14:54:30.620219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5a8717d0cd'
down_revision: Union[str, None] = '978aa1ff34a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'alembic_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('alembic_check', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
